import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    welcome: 'Welcome to BUWAD',
    selectLanguage: 'Select your language',
    english: 'English',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Solar Fish Dryer',
    rainDetected: 'RAIN ALERT',
    enclosureSecured: 'COVER IS SAFE',
    environmentalData: 'CURRENT CONDITIONS',
    temperature: 'TEMPERATURE',
    humidity: 'HUMIDITY',
    sunlight: 'SUNLIGHT',
    rainSensor: 'RAIN SENSOR',
    systemState: 'DRYER STATUS',
    phase2ActiveFlipping: 'FLIPPING FISH',
    scheduler: 'TIMING',
    status: 'STATUS',
    nextFlip: 'NEXT FLIP',
    dryingParameters: 'DRYING SETTINGS',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Thick fish · Slower flipping',
    anchoviesSmallMass: 'Small fish · Faster flipping',
    flipMechanism: 'FLIP MECHANISM',
    manualOverride: 'FLIP NOW',
    triggersImmediateFlip: 'Press to flip the fish immediately',
    criticalNotifications: 'ALERTS',
    active: 'ACTIVE',
    dismiss: 'DISMISS',
    noActiveAlerts: 'NO ACTIVE ALERTS',
    allSystemsOperational: 'ALL SYSTEMS GOOD',
    resolved: 'RESOLVED',
    activityFeed: 'ACTIVITY LOG',
    entries: 'RECORDS',
    noActivityRecorded: 'NO ACTIVITY YET',
    systemEventsWillAppear: 'Events will show here',
    dashboard: 'HOME',
    controls: 'CONTROLS',
    alerts: 'ALERTS',
    logs: 'HISTORY',
    dismissedAlerts: 'DISMISSED ALERTS',
    systemReady: 'SYSTEM READY',
    allSystemsNominal: 'ALL SYSTEMS NOMINAL',
    dryingCycleStarted: 'DRYING CYCLE STARTED',
    phase2Active: 'PHASE 2 ACTIVE',
    noAdditionalDetails: 'No additional details available',
    manual: 'MANUAL',
    sensor: 'SENSOR',
    system: 'SYSTEM',
    all: 'ALL',
    high: 'HIGH',
    medium: 'MEDIUM',
    normal: 'NORMAL',
    info: 'INFO',
    rainProtocolActivated: 'RAIN PROTOCOL ACTIVE',
    moistureDetectedEnclosureSecured: 'Moisture detected - Enclosure secured',
    coverSafe: 'COVER SAFE',
    wet: 'WET',
    dry: 'DRY'
  },
  tl: {
    welcome: 'Maligayang pagdating sa BUWAD',
    selectLanguage: 'Piliin ang iyong wika',
    english: 'English',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Solar Fish Dryer',
    rainDetected: 'ALERTS SA ULAN',
    enclosureSecured: 'LIGTAS ANG TAKIP',
    environmentalData: 'KASALUKUYANG KUNDISYON',
    temperature: 'TEMPERATURA',
    humidity: 'HUMIDIDAD',
    sunlight: 'SINAG NG ARAW',
    rainSensor: 'SENSOR NG ULAN',
    systemState: 'ESTADO NG PATUYO',
    phase2ActiveFlipping: 'BINIBALIKTAD ANG ISDA',
    scheduler: 'ORAS',
    status: 'ESTADO',
    nextFlip: 'SUSUNOD NA BALIKTAD',
    dryingParameters: 'SETTING NG PATUYO',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Makapal na isda · Mas mabagal na baliktad',
    anchoviesSmallMass: 'Maliit na isda · Mas mabilis na baliktad',
    flipMechanism: 'MEKANISMO NG PAGBALIKTAD',
    manualOverride: 'BALIKTARIN NGAYON',
    triggersImmediateFlip: 'Pindutin para baliktarin agad ang isda',
    criticalNotifications: 'MGA ALERTS',
    active: 'AKTIBO',
    dismiss: 'TANGGALIN',
    noActiveAlerts: 'WALANG AKTIBONG ALERTS',
    allSystemsOperational: 'LAHAT NG SISTEMA AY MAAYOS',
    resolved: 'NAAYOS',
    activityFeed: 'TALA NG GAWAIN',
    entries: 'MGA TALA',
    noActivityRecorded: 'WALA PANG GAWAIN',
    systemEventsWillAppear: 'Lalabas dito ang mga pangyayari',
    dashboard: 'HOME',
    controls: 'KONTROL',
    alerts: 'MGA ALERTS',
    logs: 'KASAYSAYAN',
    dismissedAlerts: 'MGA TINANGGAL NA ALERTS',
    systemReady: 'HANDA NA ANG SISTEMA',
    allSystemsNominal: 'NORMAL ANG LAHAT NG SISTEMA',
    dryingCycleStarted: 'NASIMULAN NA ANG PAGPAPATUYO',
    phase2Active: 'YUGTO 2 AKTIBO',
    noAdditionalDetails: 'Walang karagdagang detalye',
    manual: 'MANWAL',
    sensor: 'SENSOR',
    system: 'SISTEMA',
    all: 'LAHAT',
    high: 'MATAAS',
    medium: 'KATAMTAMAN',
    normal: 'NORMAL',
    info: 'IMPORMASYON',
    rainProtocolActivated: 'PROTOKOL SA ULAN AKTIBO',
    moistureDetectedEnclosureSecured: 'May nakitang halumigmig - Ligtas ang takip',
    coverSafe: 'LIGTAS ANG TAKIP',
    wet: 'BASA',
    dry: 'TUYO'
  },
  ceb: {
    welcome: 'Maayong pag-abot sa BUWAD',
    selectLanguage: 'Pilia ang imong pinulongan',
    english: 'English',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Solar Fish Dryer',
    rainDetected: 'ALERTS SA ULAN',
    enclosureSecured: 'SEGURO ANG TABON',
    environmentalData: 'KARON NGA KUNDISYON',
    temperature: 'TEMPERATURA',
    humidity: 'KABASA',
    sunlight: 'KAINIT SA ADLAW',
    rainSensor: 'SENSOR SA ULAN',
    systemState: 'ESTADO SA PAGPA-UGA',
    phase2ActiveFlipping: 'GIBALI-BALI ANG ISDA',
    scheduler: 'ORAS',
    status: 'ESTADO',
    nextFlip: 'SUNOD NGA BALI',
    dryingParameters: 'SETTING SA PAGPA-UGA',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Bagang isda · Hinay nga pagbali',
    anchoviesSmallMass: 'Gamay nga isda · Paspas nga pagbali',
    flipMechanism: 'MEKANISMO SA PAGBALI',
    manualOverride: 'BALIHON KARON',
    triggersImmediateFlip: 'Pindota para balihon dayon ang isda',
    criticalNotifications: 'MGA PAHIBALO',
    active: 'AKTIBO',
    dismiss: 'TANGTANGON',
    noActiveAlerts: 'WALAY AKTIBONG PAHIBALO',
    allSystemsOperational: 'TANANG SISTEMA MAOYOS',
    resolved: 'NA-AYO NA',
    activityFeed: 'TALA SA KALIHOKAN',
    entries: 'MGA TALA',
    noActivityRecorded: 'WALA PAY KALIHOKAN',
    systemEventsWillAppear: 'Makita dinhi ang mga panghitabo',
    dashboard: 'HOME',
    controls: 'KONTROL',
    alerts: 'MGA PAHIBALO',
    logs: 'KASAYSAYAN',
    dismissedAlerts: 'MGA GITANGGAL NGA PAHIBALO',
    systemReady: 'ANDAM NA ANG SISTEMA',
    allSystemsNominal: 'NORMAL ANG TANANG SISTEMA',
    dryingCycleStarted: 'NISUGOD NA ANG PAGPA-UGA',
    phase2Active: 'YUGTO 2 AKTIBO',
    noAdditionalDetails: 'Walay dugang detalye',
    manual: 'MANWAL',
    sensor: 'SENSOR',
    system: 'SISTEMA',
    all: 'TANAN',
    high: 'TAAS',
    medium: 'KATAMTAMAN',
    normal: 'NORMAL',
    info: 'IMPORMASYON',
    rainProtocolActivated: 'PROTOKOL SA ULAN AKTIBO',
    moistureDetectedEnclosureSecured: 'Nakit-an ang basa - Seguro ang tabon',
    coverSafe: 'SEGURO ANG TABON',
    wet: 'BASA',
    dry: 'UGA'
  },
  es: {
    welcome: 'Bienvenido a BUWAD',
    selectLanguage: 'Selecciona tu idioma',
    english: 'Inglés',
    tagalog: 'Tagalo',
    cebuano: 'Cebuano',
    systemTitle: 'Secador Solar de Pescado',
    rainDetected: 'ALERTA DE LLUVIA',
    enclosureSecured: 'CUBIERTA SEGURA',
    environmentalData: 'CONDICIONES ACTUALES',
    temperature: 'TEMPERATURA',
    humidity: 'HUMEDAD',
    sunlight: 'LUZ SOLAR',
    rainSensor: 'SENSOR DE LLUVIA',
    systemState: 'ESTADO DEL SECADOR',
    phase2ActiveFlipping: 'VOLTEANDO PESCADO',
    scheduler: 'TIEMPO',
    status: 'ESTADO',
    nextFlip: 'PRÓXIMO VOLTEO',
    dryingParameters: 'CONFIGURACIÓN DE SECADO',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Pescado grueso · Volteo lento',
    anchoviesSmallMass: 'Pescado pequeño · Volteo rápido',
    flipMechanism: 'MECANISMO DE VOLTEO',
    manualOverride: 'VOLTEAR AHORA',
    triggersImmediateFlip: 'Presiona para voltear el pescado',
    criticalNotifications: 'ALERTAS',
    active: 'ACTIVO',
    dismiss: 'DESCARTAR',
    noActiveAlerts: 'SIN ALERTAS ACTIVAS',
    allSystemsOperational: 'TODO FUNCIONA BIEN',
    resolved: 'RESUELTO',
    activityFeed: 'REGISTRO DE ACTIVIDAD',
    entries: 'REGISTROS',
    noActivityRecorded: 'SIN ACTIVIDAD',
    systemEventsWillAppear: 'Los eventos aparecerán aquí',
    dashboard: 'INICIO',
    controls: 'CONTROLES',
    alerts: 'ALERTAS',
    logs: 'HISTORIAL',
    dismissedAlerts: 'ALERTAS DESCARTADAS',
    systemReady: 'SISTEMA LISTO',
    allSystemsNominal: 'TODO NOMINAL',
    dryingCycleStarted: 'CICLO DE SECADO INICIADO',
    phase2Active: 'FASE 2 ACTIVA',
    noAdditionalDetails: 'Sin detalles adicionales',
    manual: 'MANUAL',
    sensor: 'SENSOR',
    system: 'SISTEMA',
    all: 'TODO',
    high: 'ALTO',
    medium: 'MEDIO',
    normal: 'NORMAL',
    info: 'INFO',
    rainProtocolActivated: 'PROTOCOLO DE LLUVIA ACTIVO',
    moistureDetectedEnclosureSecured: 'Humedad detectada - Cubierta segura',
    coverSafe: 'CUBIERTA SEGURA',
    wet: 'MOJADO',
    dry: 'SECO'
  },
  fr: {
    welcome: 'Bienvenue à BUWAD',
    selectLanguage: 'Choisissez votre langue',
    english: 'Anglais',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Séchoir Solaire à Poisson',
    rainDetected: 'ALERTE PLUIE',
    enclosureSecured: 'COUVERCLE SÉCURISÉ',
    environmentalData: 'CONDITIONS ACTUELLES',
    temperature: 'TEMPÉRATURE',
    humidity: 'HUMIDITÉ',
    sunlight: 'LUMIÈRE SOLAIRE',
    rainSensor: 'CAPTEUR DE PLUIE',
    systemState: 'ÉTAT DU SÉCHOIR',
    phase2ActiveFlipping: 'RETOURNEMENT DU POISSON',
    scheduler: 'MINUTERIE',
    status: 'STATUT',
    nextFlip: 'PROCHAIN RETOURNEMENT',
    dryingParameters: 'PARAMÈTRES DE SÉCHAGE',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Poisson épais · Retournement lent',
    anchoviesSmallMass: 'Petit poisson · Retournement rapide',
    flipMechanism: 'MÉCANISME DE RETOURNEMENT',
    manualOverride: 'RETOURNER MAINTENANT',
    triggersImmediateFlip: 'Appuyez pour retourner le poisson',
    criticalNotifications: 'ALERTES',
    active: 'ACTIF',
    dismiss: 'IGNORER',
    noActiveAlerts: 'AUCUNE ALERTE ACTIVE',
    allSystemsOperational: 'TOUT FONCTIONNE',
    resolved: 'RÉSOLU',
    activityFeed: 'JOURNAL D\'ACTIVITÉ',
    entries: 'ENTRÉES',
    noActivityRecorded: 'AUCUNE ACTIVITÉ',
    systemEventsWillAppear: 'Les événements apparaîtront ici',
    dashboard: 'ACCUEIL',
    controls: 'COMMANDES',
    alerts: 'ALERTES',
    logs: 'HISTORIQUE',
    dismissedAlerts: 'ALERTES IGNORÉES',
    systemReady: 'SYSTÈME PRÊT',
    allSystemsNominal: 'TOUT NOMINAL',
    dryingCycleStarted: 'CYCLE DE SÉCHAGE DÉMARRÉ',
    phase2Active: 'PHASE 2 ACTIVE',
    noAdditionalDetails: 'Aucun détail supplémentaire',
    manual: 'MANUEL',
    sensor: 'CAPTEUR',
    system: 'SYSTÈME',
    all: 'TOUT',
    high: 'ÉLEVÉ',
    medium: 'MOYEN',
    normal: 'NORMAL',
    info: 'INFO',
    rainProtocolActivated: 'PROTOCOLE PLUIE ACTIF',
    moistureDetectedEnclosureSecured: 'Humidité détectée - Couvercle sécurisé',
    coverSafe: 'COUVERCLE SÉCURISÉ',
    wet: 'MOUILLÉ',
    dry: 'SEC'
  },
  de: {
    welcome: 'Willkommen bei BUWAD',
    selectLanguage: 'Wählen Sie Ihre Sprache',
    english: 'Englisch',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Solarer Fischtrockner',
    rainDetected: 'REGENALARM',
    enclosureSecured: 'ABDECKUNG SICHER',
    environmentalData: 'AKTUELLE BEDINGUNGEN',
    temperature: 'TEMPERATUR',
    humidity: 'LUFTFEUCHTIGKEIT',
    sunlight: 'SONNENLICHT',
    rainSensor: 'REGENSENSOR',
    systemState: 'TROCKNERSTATUS',
    phase2ActiveFlipping: 'FISCH WIRD GEWENDET',
    scheduler: 'ZEITGEBER',
    status: 'STATUS',
    nextFlip: 'NÄCHSTES WENDEN',
    dryingParameters: 'TROCKNUNGSEINSTELLUNGEN',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Dicker Fisch · Langsameres Wenden',
    anchoviesSmallMass: 'Kleiner Fisch · Schnelleres Wenden',
    flipMechanism: 'WENDEMECHANISMUS',
    manualOverride: 'JETZT WENDEN',
    triggersImmediateFlip: 'Drücken zum sofortigen Wenden',
    criticalNotifications: 'ALARME',
    active: 'AKTIV',
    dismiss: 'SCHLIESSEN',
    noActiveAlerts: 'KEINE AKTIVEN ALARME',
    allSystemsOperational: 'ALLE SYSTEME FUNKTIONIEREN',
    resolved: 'ERLEDIGT',
    activityFeed: 'AKTIVITÄTSPROTOKOLL',
    entries: 'EINTRÄGE',
    noActivityRecorded: 'KEINE AKTIVITÄT',
    systemEventsWillAppear: 'Ereignisse erscheinen hier',
    dashboard: 'STARTSEITE',
    controls: 'STEUERUNG',
    alerts: 'ALARME',
    logs: 'VERLAUF',
    dismissedAlerts: 'GESCHLOSSENE ALARME',
    systemReady: 'SYSTEM BEREIT',
    allSystemsNominal: 'ALLES NOMINAL',
    dryingCycleStarted: 'TROCKNUNGSZYKLUS GESTARTET',
    phase2Active: 'PHASE 2 AKTIV',
    noAdditionalDetails: 'Keine weiteren Details',
    manual: 'MANUELL',
    sensor: 'SENSOR',
    system: 'SYSTEM',
    all: 'ALLE',
    high: 'HOCH',
    medium: 'MITTEL',
    normal: 'NORMAL',
    info: 'INFO',
    rainProtocolActivated: 'REGENPROTOKOLL AKTIV',
    moistureDetectedEnclosureSecured: 'Feuchtigkeit erkannt - Abdeckung sicher',
    coverSafe: 'ABDECKUNG SICHER',
    wet: 'NASS',
    dry: 'TROCKEN'
  },
  it: {
    welcome: 'Benvenuto su BUWAD',
    selectLanguage: 'Seleziona la tua lingua',
    english: 'Inglese',
    tagalog: 'Tagalog',
    cebuano: 'Cebuano',
    systemTitle: 'Essiccatore Solare per Pesce',
    rainDetected: 'ALLERTA PIOGGIA',
    enclosureSecured: 'COPERCHIO SICURO',
    environmentalData: 'CONDIZIONI ATTUALI',
    temperature: 'TEMPERATURA',
    humidity: 'UMIDITÀ',
    sunlight: 'LUCE SOLARE',
    rainSensor: 'SENSORE PIOGGIA',
    systemState: 'STATO ESSICCATORE',
    phase2ActiveFlipping: 'GIRANDO IL PESCE',
    scheduler: 'TIMER',
    status: 'STATO',
    nextFlip: 'PROSSIMO GIRO',
    dryingParameters: 'IMPOSTAZIONI ESSICCAZIONE',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Pesce spesso · Giro lento',
    anchoviesSmallMass: 'Pesce piccolo · Giro veloce',
    flipMechanism: 'MECCANISMO DI GIRATURA',
    manualOverride: 'GIRA ORA',
    triggersImmediateFlip: 'Premi per girare il pesce',
    criticalNotifications: 'ALLERTE',
    active: 'ATTIVO',
    dismiss: 'IGNORA',
    noActiveAlerts: 'NESSUN ALLERTA ATTIVO',
    allSystemsOperational: 'TUTTO FUNZIONA',
    resolved: 'RISOLTO',
    activityFeed: 'REGISTRO ATTIVITÀ',
    entries: 'REGISTRAZIONI',
    noActivityRecorded: 'NESSUNA ATTIVITÀ',
    systemEventsWillAppear: 'Gli eventi appariranno qui',
    dashboard: 'HOME',
    controls: 'CONTROLLI',
    alerts: 'ALLERTE',
    logs: 'CRONOLOGIA',
    dismissedAlerts: 'ALLERTE IGNORATE',
    systemReady: 'SISTEMA PRONTO',
    allSystemsNominal: 'TUTTO NOMINALE',
    dryingCycleStarted: 'CICLO DI ESSICCAZIONE AVVIATO',
    phase2Active: 'FASE 2 ATTIVA',
    noAdditionalDetails: 'Nessun dettaglio aggiuntivo',
    manual: 'MANUALE',
    sensor: 'SENSORE',
    system: 'SISTEMA',
    all: 'TUTTO',
    high: 'ALTO',
    medium: 'MEDIO',
    normal: 'NORMALE',
    info: 'INFO',
    rainProtocolActivated: 'PROTOCOLLO PIOGGIA ATTIVO',
    moistureDetectedEnclosureSecured: 'Umidità rilevata - Coperchio sicuro',
    coverSafe: 'COPERCHIO SICURO',
    wet: 'BAGNATO',
    dry: 'ASCIUTTO'
  },
  pt: {
    welcome: 'Bem-vindo ao BUWAD',
    selectLanguage: 'Selecione seu idioma',
    english: 'Inglês',
    tagalog: 'Tagalo',
    cebuano: 'Cebuano',
    systemTitle: 'Secador Solar de Peixe',
    rainDetected: 'ALERTA DE CHUVA',
    enclosureSecured: 'COBERTURA SEGURA',
    environmentalData: 'CONDIÇÕES ATUAIS',
    temperature: 'TEMPERATURA',
    humidity: 'UMIDADE',
    sunlight: 'LUZ SOLAR',
    rainSensor: 'SENSOR DE CHUVA',
    systemState: 'ESTADO DO SECADOR',
    phase2ActiveFlipping: 'VIRANDO O PEIXE',
    scheduler: 'TEMPORIZADOR',
    status: 'ESTADO',
    nextFlip: 'PRÓXIMA VIRADA',
    dryingParameters: 'CONFIGURAÇÕES DE SECAGEM',
    danggit: 'DANGGIT',
    bolinao: 'BOLINAO',
    rabbitfishThickFillet: 'Peixe grosso · Virada lenta',
    anchoviesSmallMass: 'Peixe pequeno · Virada rápida',
    flipMechanism: 'MECANISMO DE VIRADA',
    manualOverride: 'VIRAR AGORA',
    triggersImmediateFlip: 'Pressione para virar o peixe',
    criticalNotifications: 'ALERTAS',
    active: 'ATIVO',
    dismiss: 'DISPENSAR',
    noActiveAlerts: 'NENHUM ALERTA ATIVO',
    allSystemsOperational: 'TUDO FUNCIONANDO',
    resolved: 'RESOLVIDO',
    activityFeed: 'REGISTRO DE ATIVIDADE',
    entries: 'REGISTROS',
    noActivityRecorded: 'NENHUMA ATIVIDADE',
    systemEventsWillAppear: 'Eventos aparecerão aqui',
    dashboard: 'INÍCIO',
    controls: 'CONTROLES',
    alerts: 'ALERTAS',
    logs: 'HISTÓRICO',
    dismissedAlerts: 'ALERTAS DISPENSADAS',
    systemReady: 'SISTEMA PRONTO',
    allSystemsNominal: 'TUDO NOMINAL',
    dryingCycleStarted: 'CICLO DE SECAGEM INICIADO',
    phase2Active: 'FASE 2 ATIVA',
    noAdditionalDetails: 'Sem detalhes adicionais',
    manual: 'MANUAL',
    sensor: 'SENSOR',
    system: 'SISTEMA',
    all: 'TODOS',
    high: 'ALTO',
    medium: 'MÉDIO',
    normal: 'NORMAL',
    info: 'INFO',
    rainProtocolActivated: 'PROTOCOLO DE CHUVA ATIVO',
    moistureDetectedEnclosureSecured: 'Umidade detectada - Cobertura segura',
    coverSafe: 'COBERTURA SEGURA',
    wet: 'MOLHADO',
    dry: 'SECO'
  }
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [hasSelectedLanguage, setHasSelectedLanguage] = useState(false);
  const [onLanguageSelectedCallback, setOnLanguageSelectedCallback] = useState(null);

  useEffect(() => {
    const savedLang = localStorage.getItem('buwad_language');
    const savedPreference = localStorage.getItem('buwad_save_language');
    
    if (savedLang && savedPreference === 'true') {
      setLanguage(savedLang);
      setHasSelectedLanguage(true);
    }
  }, []);

  const t = (key) => {
    const translation = translations[language]?.[key];
    if (translation) return translation;
    return translations.en[key] || key;
  };

  const selectLanguage = (lang, save = false) => {
    setLanguage(lang);
    setHasSelectedLanguage(true);
    
    if (save) {
      localStorage.setItem('buwad_language', lang);
      localStorage.setItem('buwad_save_language', 'true');
    } else {
      localStorage.removeItem('buwad_language');
      localStorage.removeItem('buwad_save_language');
    }
    
    if (onLanguageSelectedCallback) {
      onLanguageSelectedCallback();
    }
  };

  const resetLanguage = () => {
    setHasSelectedLanguage(false);
    setLanguage('en');
    localStorage.removeItem('buwad_language');
    localStorage.removeItem('buwad_save_language');
  };

  const registerLanguageCallback = (callback) => {
    setOnLanguageSelectedCallback(() => callback);
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      t, 
      selectLanguage, 
      hasSelectedLanguage, 
      resetLanguage,
      registerLanguageCallback
    }}>
      {children}
    </LanguageContext.Provider>
  );
};